#optim:
#  type: torch.optim.AdamW
#  params:
#    lr: 1e-3
#    weight_decay: 0.003
#    amsgrad: True
#    betas: [ 0.9, 0.999 ]
#    eps: 1e-08

optim:
  type: monai.optimizers.Novograd
  params:
    lr: 1e-3
    weight_decay: 0.003
    amsgrad: True